echo Setting up replication ...
(set -x; maprcli stream replica autosetup -path /mapr/edge.df70.com/apps/pipeline/data/replicatedStream -replica /mapr/core.df70.com/apps/pipeline/data/replicatedStream -multimaster true)
